# Generated by Django 6.0.7 on 2026-07-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='phone',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
